## https://docs.aws.amazon.com/ko_kr/lambda/latest/dg/API_UpdateFunctionCode.html



name: Build and Deploy to Amazon Lambda

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]


permissions:
  contents: read

jobs:
  build:
    # 1. mkdir package
    # 2. pip install --target ./package -r requirements.txt
    # 3. zip -r ./my_deployment_package.zip ./package
    # 4. yes | cp -r ./source/target_source.py ./lambda_function.py
    # 5. zip ./my_deployment_package.zip ./lambda_function.py
    # 6. upload to S3 ./my_deployment_package.zip    name: create the deployment package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          mkdir package
          pip install --target package -r requirements.txt

      - name: create zip
        run: |
          cd package
          zip -r ../lambda_hashtags.zip .
          cd ../source
          zip ../lambda_accounts.zip utils.py
          yes | cp -r ../lambda_accounts.zip ../lambda_hashtags.zip
          yes | cp -r lambda_accounts.py lambda_function.py
          zip ../lambda_accounts.zip lambda_function.py
          yes | cp -r lambda_hashtags.py lambda_function.py
          zip ../lambda_hashtags.zip lambda_function.py
          cd ..

      - name: crediential aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: upload s3
        run: |
           aws s3 cp lambda_accounts.zip s3://de-2-1-s3/test/file.zip
           aws s3 cp lambda_hashtags.zip s3://de-2-1-s3/test/file.zip
