# check for
# - package requirements
# - required files exist
# - aws cli credential

name: Build and Deploy Check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


permissions:
  contents: read

env:
  REGION: us-west-2
  ACCOUNTS_FUNCTION_NAME: DE-2-1-extract-accounts
  HASHTAGS_FUNCTION_NAME: DE-2-1-extract-hashtags

jobs:
  package_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          mkdir package
          pip install --target package -r requirements.txt

  require_file_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check file exists
        run: |
          files=$(find / -type f -name "required_files.txt")
          
          for file in $files; do
            echo "Processing file: $file"
            if [ -f $file_name ]; then
              echo "File exists: $file_name"
            else
              echo "File does not exist: $file_name"
              exit 1
            fi
          done
#          file_name="/configure.ini"
#          if [ -f $file_name ]; then
#            echo "File exists: $file_name"
#          else
#            echo "File does not exist: $file_name"
#            exit 1
#          fi
#
#          file_name="/source/utils.py"
#          if [ -f $file_name ]; then
#            echo "File exists: $file_name"
#          else
#            echo "File does not exist: $file_name"
#            exit 1
#          fi
#
#          file_name="/source/lambda_accounts.py"
#          if [ -f $file_name ]; then
#            echo "File exists: $file_name"
#          else
#            echo "File does not exist: $file_name"
#            exit 1
#          fi
#
#          file_name="/source/lambda_hashtags.py"
#          if [ -f $file_name ]; then
#            echo "File exists: $file_name"
#          else
#            echo "File does not exist: $file_name"
#            exit 1
#          fi

  aws_credential_check:
    runs-on: ubuntu-latest

    steps:
      - name: credential aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}