# check for
# - package requirements
# - required files exist
# - aws cli credential

name: Build and Deploy Check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


permissions:
  contents: read


jobs:
  package_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          mkdir package
          pip install --target package -r requirements.txt

  require_file_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check file exists
        run: |
          files=$(cat "required_files.txt")
          
          for file in $files; do
            if [ -f ${file//[$'\r']} ]; then
              echo "File exists: $file"
            else
              echo "File does not exist: $file"
              exit 1
            fi
          done

  aws_credential_check:
    runs-on: ubuntu-latest

    steps:
      - name: credential aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}